spring:
  datasource:
    url: jdbc:mysql://192.168.121.130:3306/family_cloud
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.121.130
      port: 6379
      password: 123456
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.jian.family: debug
minio:
  entrypoint: http://192.168.121.130:9000
  access-key: minioadmin
  secret-key: minioadmin